apiVersion: 0.1
kind: Service
metadata:
  name: hlw-api
  labels:
    app: hlw
    tier: hlw-api
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 3000
  selector:
    app: hlw
    tier: hlw-api
